# Generated by Django 4.2.27 on 2026-01-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for visit', null=True)),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('checking', 'Checking'), ('examined', 'Examined'), ('completed', 'Completed')], default='waiting', max_length=20)),
                ('notes', models.TextField(blank=True, help_text="Doctor's notes", null=True)),
                ('next_visit_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['visit_time'],
            },
        ),
    ]
