# Generated by Django 5.2 on 2026-01-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-priority_score', 'visit_time']},
        ),
        migrations.AddField(
            model_name='patient',
            name='health_status',
            field=models.CharField(choices=[('critical', 'Critical'), ('mild', 'Mild'), ('normal', 'Normal'), ('unknown', 'Unknown')], default='unknown', help_text='Auto-calculated based on latest measurements', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_assessment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='priority_score',
            field=models.IntegerField(default=0, help_text='Higher score = higher priority (0-100)'),
        ),
    ]
