# Generated by Django 4.2.28 on 2026-03-05 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('health_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('next_visit_date', models.DateField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_history', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Visit History',
                'verbose_name_plural': 'Visit Histories',
                'ordering': ['-visit_time'],
            },
        ),
    ]
