# Generated by Django 4.2.28 on 2026-03-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_visithistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default='', editable=False, help_text='Unique hospital ID (e.g., PAT001)', max_length=20, unique=True),
        ),
    ]
