# Generated by Django 4.2.28 on 2026-03-06 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, help_text='When patient provided consent', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='consent_version',
            field=models.CharField(default='1.0', help_text='Version of privacy policy patient consented to', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='data_collection_consent',
            field=models.BooleanField(default=False, help_text='Patient consents to collection and storage of personal/health information'),
        ),
        migrations.AddField(
            model_name='patient',
            name='data_usage_consent',
            field=models.BooleanField(default=False, help_text='Patient consents to medical information being accessed by authorized staff'),
        ),
        migrations.AddField(
            model_name='patient',
            name='portal_consent_given',
            field=models.BooleanField(default=False, help_text='Whether patient has given consent on first portal login'),
        ),
        migrations.AddField(
            model_name='patient',
            name='privacy_policy_acknowledged',
            field=models.BooleanField(default=False, help_text='Patient acknowledges reading and understanding privacy policy'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(editable=False, help_text='Unique hospital ID (e.g., PAT001)', max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CONSENT_GRANTED', 'Consent Granted'), ('CONSENT_UPDATED', 'Consent Updated'), ('CONSENT_WITHDRAWN', 'Consent Withdrawn'), ('PORTAL_CONSENT_GRANTED', 'Portal Consent Granted')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('consent_version', models.CharField(default='1.0', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('data_collection_consent', models.BooleanField(default=False)),
                ('data_usage_consent', models.BooleanField(default=False)),
                ('privacy_policy_acknowledged', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about consent action', null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_logs', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Consent Log',
                'verbose_name_plural': 'Consent Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
