# Generated by Django 4.2.27 on 2026-01-07 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('blood_pressure', models.CharField(blank=True, help_text='Format: systolic/diastolic (e.g., 120/80)', max_length=20, null=True)),
                ('temperature', models.FloatField(blank=True, help_text='Temperature in Celsius', null=True)),
                ('spo2', models.FloatField(blank=True, help_text='Blood oxygen saturation in percentage', null=True)),
                ('heart_rate', models.FloatField(blank=True, help_text='Heart rate in beats per minute', null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('device', 'IoT Device')], default='manual', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='patients.patient')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
