# Generated by Django 4.2.27 on 2026-01-07 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='prescription', serialize=False, to='patients.patient')),
                ('medicines', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
