# Generated by Django 4.2.27 on 2026-01-19 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_alter_patient_options_patient_health_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_image', models.ImageField(help_text='Medical report image (jpg, png, pdf)', upload_to='reports/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(default='system', help_text='User who uploaded the report', max_length=100)),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('extracted_text', models.TextField(blank=True, help_text='Full text extracted from the report using OCR', null=True)),
                ('key_phrases', models.JSONField(blank=True, help_text='Key medical phrases extracted from the report', null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Overall confidence score of the OCR analysis', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if analysis failed', null=True)),
                ('doctor_notes', models.TextField(blank=True, help_text="Doctor's notes about this report", null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='patients.patient')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
