# Generated by Django 4.2.27 on 2026-01-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_image',
            field=models.FileField(help_text='Medical report (jpg, png, pdf)', upload_to='reports/%Y/%m/%d/'),
        ),
    ]
