#define secret_ssid "Your Wifi SSID"
#define secret_password "Your Wifi Password"
#define secret_deviceId "Your Device ID"
#define secret_ip "Your Local Device or Deployment Server"
#define secret_port "Your Port"